public class Testtrycatch2
{
	public static void main(String args[])
	{
		try{
			int data=50/0;
			}catch(Exception e){System.out.println(e);}
		System.out.println("rest of the code");
	}
}
/*java multi catch block - only one catch block executes int a = new int[5]; index 0-4
a[5]=30/0;    arithematic exception
exception e s super of arrayoutofbound and arithematic
complite time error when super block is declared 
subclasses then
superclasses
to avoid compile error
nested try & catch 







*/